var stories = {
	j3 :[ 	"Texas Governor Declares State of Disaster because of floods",
		"Wildfire Aftermath in Canada",
		"The Study of Air Quality in South Korea"],
	j2 :[	"EgyptAir Flight 804: \"Black Box\" Signals Detected",
		"U.S. Government Warns of Travel to Europe",
		"Ethical Hackers Test An Organization's Security"],
	j1 :[	"Unique Challenges Complicate the Upcoming Olympics in Rio",
		"NOAA Releases Its Hurricane Forecast",
		"How Digital Technology Revolutionized Photography"],
	m31 :[	"An International Migrant Crisis",
		"The Battle for Falluja Rages On",
		"The History and Traditions of Memorial Day",
		"The Threat of Superbugs"],
	m30 :["Weekend"],m29 :["Weekend"],m28 :["Weekend"],
	m27 :[	"President Obama Heads to Hiroshima",
		"Taliban Names New Leader",
		"Trump Clinches GOP Nomination",
		"Solutions to America's Crumbling Infastructure"],
	m26 :[	"G7 Leaders Meet in Japan",
		"The Global Arms Trade"],
	m25 :[	"The Fight for the Iraqui City of Falluja",
		"A Shakeup at the TSA",
		"The Historic Invention of the Barcode"],
	m24 :[	"Four Climbers Dead on Everest",
		"Egypt's Tourism Drops Following Recent Events",
		"Yellow Fever Outbreak Hits Angola",
		"A Researcher Promotes Spider Silk"],
	m23 :[	"President Obama Arrives in Vietnam",
		"Egypt Struggles in the Wake of Recent Evenets",
		"U.S. Federal Judge Orders Cleveland, Mississippi Schools to Desegregate"],
	m22 :["Weekend"], m21 :["Weekend"],
	m20 :[	"International Officials Search the Mediterranean for the Wreckage of EgyptAir Flight 804",
		"The Hunt for Mosquitoes in Puerto Rico"],
	m19 :[	"A Kidnapped Nigerian Schoolgirl Finds Freedom",
		"Debate Surrounding a Possible British Exit from E.U."],
	m18 :[	"U.S. Fighter Travel to Romania Amid Black Sea Tensions",
		"TSA Works to Reduce Airport Security Waits",
		"Alarm Clock History"],
	m17 :[	"Deepening Crisis in Venezuela",
		"Efforts to Remove Mines from the Holy Land",
		"Recalls of Frozen Products Over Listeria Continue",
		"Possible Future Uses of Drones"],
	m16 :[	"Changes at the TSA",
		"Fed Issue Guidance on Transgender Acces to School Bathrooms",
		"Queen Elizabeth II's Two Birthdays",
		"A Facebook Investigation"],
	m15 :["Weekend"],m14 :["Weekend"],
	m13 :[	"Killer Heatwave Wreaks Havoc in Southeast Aisa",
		"The Summiting of Mount Everest",
		"The Underwater Cable System that Connects the World"],
	m12 :[	"Takeaways from West Virginia and Nebraska",
		"The Significance of Political Turmoil in Brazil",
		"How You Can Help Break the Mosquito Lifecycle"],
	m11 :[	"U.S. Destroyer Sails Near Disputed Chinese Island",
		"Obaba to Make Historic Visit to Hiroshima",
		"Inside Fire-Ravaged Fort McMurray"],
	m10 :[	"Swarm of Earthquakes Strikes Mount St. Helens",
		"North Carolina's Controversial \"Bathroom Law\"",
		"A Character Study: Blind Adventurer"],
	m9 :[	"A High Level Gathering Takes Place in North Korea",
		"Fort McMurray Wildfire Affects Land and Sky in Canada",
		"Why Are Opioids Addictive?"],
	m8 :["Weekend"],m7 :["Weekend"],
	m6 :[	"International Military Power is Built Up and Around Black Sea",
		"CNN Visits Nuclear Submarine"],
	m5 :[	"Economic Crisis Takes a Toll on Venezuela",
		"\"Explosive\" Fire Threatens a City in Canada",
		"Major Developments in U.S. Politics"],
	m4 :[	"Navy SEAL Killed in Iraq",
		"Hundreds of Teachers Protest in Detroit",
		"A Study Looks Into Mobile Addiction Among Teengers"],
	m3 :[	"Puerto Ricans Leaving Island for U.S. in Record Numbers",
		"Historic U.S. Cruise Docks in Havana",
		"Interview with a Former Prisoner of North Korea"],
	m2 :[	"Kenyan Officials Burn Tons of Ivory to Send a Message",
		"Rio Olympics",
		"South Korea Unveils Anti-Zika Uniform",
		"Dermatologists Draw Attention to Skin Cancer",
		"The Debate Over Voting-Boothe Selfies"],
	m1 :["Weekend"],a30 :["Weekend"],
	a29 :[	"The Complicated War in Syria",
		"A Dive to the Marianas Trench",
		"Bison Closer to \"National Mammal\" Status After House Vote"],
	a28 :[	"Ted Cruz Names Carly Fiorina as VP Pick",
		"A Shift in Genorational Demographics",
		"Harvard Mumps Outbreak Grows"],
	a27 :[	"A Cheating Scandal at Mitsubushi",
		"A \"Robot Revolution\" in Japan",
		"A Character Study of A Neurosurgeon Who Exemplifies Perseverance"],
	a26:[	"More U.S. Troops in Syria",
		"Reopening of a Belgian Train Station",
		"A Dome for Chernobyl",
		"Restrains on a Mars Mission"],
	a25 :[	"North Korea Reportedly Launches A Ballistic Missile",
		"A Global Banana Crisis Looms",
		"A CNN Hero Uses Horses to Help Younge People with Special Needs"],
	a24:["Weekend"],a23:["Weekend"],
	a22 :[	"ISIS Sends Recruits to Libya",
		"Prince Passes Away on Minnesota",
		"Study of the Potential Psycological Effects of Space Travel"],
	a21 :[	"Trump & Clinton Win New York Primary",
		"Predictions are Made for the Atlantic Hurricane Season",
		"Palmyra's Ancient Triumphal Arch Resurrected in London's Trafalgar Square"],
	a20 :[	"Saudis Warn of Economic Reprisals if Congress Passes 9/11 Bill",
		"A Look Inside North Korea's Capital",
		"A Seat Aboard a Deep-Space Capsule"],
	a19 :[	"Lawmakers Debate Impeaching Brazil's President",
		"Supreme Court Examines an Executive Action on Immigration",
		"Strategies of Retailers"],
	a18 :[	"Earthquakes Claim Lives and Homes in Ecuador and Japan",
		"Divers Excavate a Historic Shipwreck Near Oman",
		"The Effects of Space on the Human Body"],
	a17:["Weekend"],a16:["Weekend"],
	a15 :[	"Russian Jets Closely Pass a U.S. Ship",
		"CNN Obtains \"Proof of Life\" Video of Missing Nigerian Schoolgirls",
		"The Methods of Influencing Delegates"],
	a14 :[	"How CDC is Tracking Zika",
		"Scientists Scurry to Southeast to Study Storms"],
	a13 :[	"Two ISIS Defectors Discuss Challenges of Fighting the ISIS",
		"How Rules are Set for the RNC",
		"Character Study Focuses on Ecological Inspiration"],
	a12 :[	"Senior North Korean Millitary Oficial Defects, South Korea Says",
		"Kerry Visits Hiroshima",
		"A Student-Made Device that Adresses Hearing Loss"],
	a11 :[	"Terrorism Suspects Arrested in Belgium",
		"Concerns About a Major Dam in Iraq",
		"SpaceX Makes Historic Rocket Landing"],
	a10:["Weekend"],a9:["Weekend"],
	a8 :[	"The U.S. Terrorist Screening Center",
		"World's First Dengue Fever Vaccine Launched in the Philippines",
		"The auction of \"Harry Potter Chair\""],
	a7 :[	"Wisconsin Primary Takeaways",
		"What is a Religious Freedom Bill?",
		"A Report on Global Use of Death Penalty",
		"A Swimmer of the Oceans Seven"],
	a6 :[	"Iceland's Prime Minister Resigns Amid Panama Papers Fallout",
		"2016 Presidential Election: Possibilities of a Contested Convention"],
	a5 :[	"New E.U. Deal Concerning Migrants is Tested",
		"Brazil Struggles to Sell Tickets for the Olympics",
		"World's Busiest Airports"],
	a4 :[	"First Passenger Flight Leaves Brussels Since March 22 Terror Attacks",
		"Lost Language Found on Buried Stone Slab",
		"Wisconsin's Political Significance",
		"New Music Theory"],
	a3:["Weekend"],a2:["Weekend"],
	a1 :[	"Global Officials Attend the Nuclear Security Summit",
		"Scientists Scurry to Southeast to Study Tornadoes",
		"Character Study Profiles a Mentor and Coach"],
	ma31 :[	"Tiny South China Sea Island Plays Role in a Large Regional Dispute",
		"Alzheimer's Caregivers Give Up Food, Medication, Education, Report Says",
		"U.S. Companies Work to Prove the Viability of the Hyperloop"],
	ma30 :[	"Obama Announces New Moves to Fight Opioid and Heroin Abuse Epidemic",
		"Californians Debate Minmum Wage Hike",
		"Pavlof Volcano in Alaska Still Erupting"],
	ma29 :[	"Terrorists Target Christians in Pakistan",
		"The Psycology of Terrorism",
		"\"Fish Kill\" in Florida"],
	ma28 :[	"\"Raw Ingrediants\""],
	ma27:["Weekend"],ma26:["Weekend"],
	ma25 :[	"Syrian Forces Fight for Palmyra",
		"Zika Virus Threatens to Spread Further"],
	ma24 :[	"Security Increased in Cities Worldwide",
		"U.S. Officials Issue Strongest Warning on Opioid Medications",
		"Tremendoud Aircraft Gets off the Ground"],
	ma23 :[	"Terrorists Target Belgium's Capital",
		"The Issue of Food Recalls"],
	ma22 :[	"Obama Meets Cuban Leader Raul Castro",
		"Why is Brazil in Such a Big Mess?",
		"American Footbal Arrives in Egypt"],
	ma21 :[	"Police Capture the Most Wanted Man in Europe",
		"Obama Visits Cuba",
		"North Korea Launches Ballistic Missiles"],
	ma20:["Weekend"], ma19:["Weekend"],
	ma18 :[	"U.S. Government Declares ISIS Commiting Genocide",
		"American Student Sentenced in North Korea",
		"SeaWorld Ends Orva Breeding Program"],
	ma17 :[	"Obama Nominates Merric Garland to Supreme Court",
		"El Nino Rain Hit's California",
		"The Science of Happiness"],
	ma16 :[ "What is a Brokered Convention?",
		"NFL Acknowledges CTE Link to Football"],
	ma15 :[	"Russia to Withdraw Forces from Syria",
		"U.S. Election: Super Tuesday 3",
		"Early Pollen Season"],
	ma14 :[	"Japanese Officials Scour Land and Sea for Radiation",
		"Researchers Hunt for Viruses in South Africa",
		"Daylight Saving Time Fast Facts"],
	ma13:["Weekend"],ma12:["Weekend"],
	ma11 :[	"Canada's Justin Trudeau Formally Visits the White House",
		"Fukushima Survivors Five Years On",
		"Scientists Grow Crops in Mars-Like Soil"],
	ma10 :[	"The War Against Zika",
		"A Total Solar Eclipse",
		"Fukishima: Five Years After Japan's Tsunami"],
	ma9 :[	"Iran Tests Missiles, U.S. Alarmed",
		"U.S. Claims to Have Killed 250 Al-Shabaab Fighters",
		"International Women's Day"],
	ma8 :[	"North Korea Threatens Nuclear Strike Over U.S.-South Korean Exercises",
		"Mideast's Worst Deought in 900 Years May Have Contributed to Syrian War",
		"The Inventor of Email Passes Away"],
	ma7 :[	"Thousands of Refugees Stuck on Macedonian Border",
		"North Korea: Nukes Need To Be Ready For Use",
		"Nancy Regan Dead at 94",
		"Ben Carson Ends Campaign"],
	ma6:["Weekend"],ma5:["Weekend"],
	ma4 :[	"North Korea Defies New U.N. Sanctions",
		"Magnitude 7.8 Earthquake Hirs Indonesia"],
	ma3 :[	"Takeaways From Super Tuesday",
		"Astronaut Scott Kelly's Homecoming",
		"Likely Piece of Doomed Flight MH370 Found, U.S. Official Says"],
	ma2 :[	"Super Tuesday Scenarios for U.S. Political Parties",
		"A Boom in Newspaper Circulation in India"],
	ma1 :[	"The Role of Animal feed in the U.S. Food Industry"],
	f29 :[	"Syria's Cessation of Hostilities",
		"Lebanon's River of Garbage",
		"Hillary Clinton Crushes Bernie Sanders in South Carolina"],
	f28:["Weekend"],f27:["Weekend"],
	f26 :[	"Iran Holds Parliamentary Elections",
		"UAE Seeds Clouds To Meet Water Needs",
		"Coast Guard Rescues Fishing Boat Crews Off New York"],
	f25 :[	"Parts of U.S. Recover from Severe Weather",
		"A Look at Life After A National Campaign"],
	f24 :[	"Obama Gives Congress Guantanamo Closure Plan",
		"Water Crisi Impacting New Delhi"],
	f23 :[	"Deadline Approaches In A Case Between U.S. Government and Apple",
		"French Law Targets Food Waste"],
	f22 :[	"Monster Cyclone Strikes Fiji",
		"A Mountain of Trash Towers Over Mumbai",
		"Qinners and Losers from South Carolina, Navada Contests"],
	f21:["Weekend"],f20:["Weekend"],
	f19 :[	"European Union Leader Meet in Belgium, Potential Divide in the U.S. Supreme Court",
		"South Carolina and Nevada Hold Nominating Contest This Saturday"],
	f18 :[	"Tension in the South China Sea",
		"Apple Opposes Judge's Order to Hack Terrorist's iPhone"],
	f17 :[	"Politics Swirl Around A Potential Supreme Court Nominee",
		"Oil-Producing Nations Consider a Strategy for a Global Glut",
		"Lasers Threaten Pilots"],
	f16 :[	"Supreme Court Justice Antonin Scalia Dies at 79",
		"Plans for a Ceasefire in Syria",
		"Pope Francis' Trip to Mexico"],
	f15:["Weekend"],f14:["Weekend"],f13:["Weekend"],
	f12 :[	"Inside Aleppo: A City on Edge",
		"Stock Market Strain"],
	f11 :[	"U.S. Supreme Court Puts on Hold Obama's Executive Action",
		"Winners and Losers of the New Hampshire Primary",
		"Scientists Listen for Gravitational Waves"],
	f10 :[	"Rescuers Search for Taiwan Earthquake Survivors",
		"Haiti Leader Resigns",
		"New Technology Aims to Follow Your Eyes"],
	f9 :[	"Strong Reactions Follow North Korean Satellite Launch",
		"A Note of Caution Ahead of Rio Olympics",
		"The New Hampshire Primaries"],
	f8 :[	"Raw Ingredients: Cereal"],
	f7:["Weekend"],f6:["Weekend"],
	f5 :[	"Obama Attends National Prayer Breakfast, Visits Mosque",
		"The Trans-Pacific Partnership",
		"School for DJs"],
	f4 :[	"The Uncertain Future of Syria",
		"The First Underwater Museum in Europe",
		"The Risks and Rewards of Super Bowl Ads"],
	f3 :[	"WHO Declares International Public Health Emergency",
		"Chinese Lunar New Year",
		"The Results of the Iowa Caucuses"],
	f2 :[	"Greeks in Forefront of European Migrant Crisis",
		"Concerns About Repeated Head Trauma"],
	f1 :[	"Massive Ship Symbolizes U.S.-China Trade",
		"The Significance of the Iowa Caucuses"],
	ja31:["Weekend"],ja30:["Weekend"],
	ja29 :[	"Experts Track \"Explosevly\" Spreading Virus in the Americas",
		"All Eyes on Iowa Ahead of State's Upcoming Caucuses"],
	ja28 :[	"A Standoff in Oregon",
		"A Cliff Crisis in California",
		"A Lesser-Known Part of Ellis Island"],
	ja27 :[	"Denmark Adopts Controversial Law",
		"The Effects of Arab Spring"],
	ja26 :[	"WHO Warns About Zika Virus in the Americas",
		"East Asia Shivers Under Cold Temperatures"],
	ja25 :[	"Millions of Americans Recover from Massice Winter Strom",
		"Trouble Brews in Burundi"],
	ja24:["Weekend"],ja23:["Weekend"],
	ja22 :[	"Lead Poisoning Concerns Abound in Flint, Michigan",
		"Forecasters Predict A Blizzard for the U.S. Capital",
		"Researchers \"Found\" a Ninth Planet"],
	ja21 :[	"At Least 19 Killed In A Pakistan University Attack",
		"A Freefall in Oil Prices",
		"Winter Storm Heads for Washington, Northeast"],
	ja20 :[	"U.S. Supreme Court Takes Up Obama's Immigration Actions",
		"Taiwan Elects First Female President",
		"Robots May Carry the Future of Home Delivery"],
	ja19 :[	"The Iran Nuclear Deal",
		"Stories Related to Martin Luther King",
		"The Largest Dinosaur on Record"],
	ja18:["Weekend"],ja17:["Weekend"],ja16:["Weekend"],
	ja15 :[	"Factors in Market Dynamics",
		"Deadly Blasts, Shootout in Indonesia",
		"Divisions in Turkey"],
	ja14 :[	"Toxic Water Crisis in Flint, Michigan",
		"Hong Kong to Phase Out Ivory Sales",
		"Rams Return to L.A."],
	ja13 :[	"Barack Obama Delivers Final state of the Union Address",
		"Governor Nikki Haley's GOP Respinse",
		"Ten Sailors In Iranian Custody"],
	ja12 :[	"Obama to Give His Final State of the Union",
		"Parts of the Brain Involved in Driving",
		"Navigate the Open Sea in a Rowboat"],
	ja11 :[	"U.S. B-52 Bomber Flies Over South Korea, Sends Warning to North Korea",
		"Hitler's \"Mein Kampf\" Republished in Germany"],
	ja10:["Weekend"],ja9:["Weekend"],
	ja8 :[	"U.S. Stocks Plummet Following Chinese Markets Drop",
		"Land Ownership Issue in U.S.",
		"El Nino Alters Winter"],
	ja7 :[	"North Korea Claims To Have Tested A Hydrogen Bomb",
		"Politicians Adress Addiction in New Hampshire"],
	ja6 :[	"Obama Announces Gun Control Executive Action",
		"The Battle for Ramadi",
		"A New Way to Explore the Oceans"],
	ja5 :[	"Diplomatic Trouble Brews Between Saudi Arabia and Iran",
		"Zika Virus Reaches Puerto Rico"],
	ja4 :[	"Storms and Flooding in the U.S.",
		"Living in Astronomy Village",
		"New Year's Celebrations Around the World"],
	ja3:["Weekend"],ja2:["Weekend"],ja1:["Weekend"]

};
