var stories = {
	j3 =[ 	"Texas Governor Declares State of Disaster because of floods",
		"Wildfire Aftermath in Canada",
		"The Study of Air Quality in South Korea"],
	j2 =[	"EgyptAir Flight 804: \"Black Box\" Signals Detected",
		"U.S. Government Warns of Travel to Europe",
		"Ethical Hackers Test An Organization's Security"],
	j1 =[	"Unique Challenges Complicate the Upcoming Olympics in Rio",
		"NOAA Releases Its Hurricane Forecast",
		"How Digital Technology Revolutionized Photography"],
	m31 =[	"An International Migrant Crisis",
		"The Battle for Falluja Rages On",
		"The History and Traditions of Memorial Day",
		"The Threat of Superbugs"],
	m30 =["Weekend"],m29 =["Weekend"],m28 =["Weekend"],
	m27 =[	"President Obama Heads to Hiroshima",
		"Taliban Names New Leader",
		"Trump Clinches GOP Nomination",
		"Solutions to America's Crumbling Infastructure"],
	m26 =[	"G7 Leaders Meet in Japan",
		"The Global Arms Trade"],
	m25 =[	"The Fight for the Iraqui Citty of Falluja",
		"A Shakeup at the TSA",
		"The Historic Invention of the Barcode"],
	m24 =[	"Four Climbers Dead on Everest",
		"Egypt's Tourism Drops Following Recent Events",
		"Yellow Fever Outbreak Hits Angola",
		"A Researcher Promotes Spider Silk"]
	m23 =[	"President Obama Arrives in Vietnam",
		"Egypt Struggles in the Wake of Recent Evenets",
		"U.S. Federal Judge Orders Cleveland, Mississippi Schools to Desegregate"],
	m22 =["Weekend"], m21 =["Weekend"],
	m20 =[	"International Officials Search the Mediterranean for the Wreckage of EgyptAir Flight 804",
		"The Hunt for Mosquitoes in Puerto Rico"],
	m19 =[	"A Kidnapped Nigerian Schoolgirl Finds Freedom",
		"Debate Surrounding a Possible British Exit from E.U."],
	m18 =[	"U.S. Fighter Travel to Romania Amid Black Sea Tensions",
		"TSA Works to Reduce Airport Security Waits",
		"Alarm Clock History"],
	m17 =[	"Deepening Crisis in Venezuela",
		"Efforts to Remove Mines from the Holy Land",
		"Recalls of Frozen Products Over Listeria Continue",
		"Possible Future Uses of Drones"],
	m16 =[	"Changes at the TSA",
		"Fed Issue Guidance on Transgender Acces to School Bathrooms",
		"Queen Elizabeth II's Two Birthdays",
		"A Facebook Investigation"],
	m15 =["Weekend"],m14 =["Weekend"],
	m13 =[	"Killer Heatwave Wreaks Havoc in Southeast Aisa",
		"The Summiting of Mount Everest",
		"The Underwater Cable System that Connects the World"],
	m12 =[	"Takeaways from West Virginia and Nebraska",
		"The Significance of Political Turmoil in Brazil",
		"How You Can Help Break the Mosquito Lifecycle"],
	m11 =[	"U.S. Destroyer Sails Near Disputed Chinese Island",
		"Obaba to Make Historic Visit to Hiroshima",
		"Inside Fire-Ravaged Fort McMurray"],
	m10 =[	"Swarm of Earthquakes Strikes Mount St. Helens",
		"North Carolina's Controversial \"Bathroom Law\"",
		"A Character Study: Blind Adventurer"],
	m9 =[	"A High Level Gathering Takes Place in North Korea",
		"Fort McMurray Wildfire Affects Land and Sky in Canada",
		"Why Are Opioids Addictive?"],
	m8 =["Weekend"],m7 =["Weekend"],
	m6 =[	"International Military Power is Built Up and Around Black Sea",
		"CNN Visits Nuclear Submarine"],
	m5 =[	"Economic Crisis Takes a Toll on Venezuela",
		"\"Explosive\" Fire Threatens a City in Canada",
		"Major Developments in U.S. Politics"],
	m4 =[	"Navy SEAL Killed in Iraq",
		"Hundreds of Teachers Protest in Detroit",
		"A Study Looks Into Mobile Addiction Among Teengers"],
	m3 =[	"Puerto Ricans Leaving Island for U.S. in Record Numbers",
		"Historic U.S. Cruise Docks in Havana",
		"Interview with a Former Prisoner of North Korea"],
	m2 =[	"Kenyan Officials Burn Tons of Ivory to Send a Message",
		"Rio Olympics",
		"South Korea Unveils Anti-Zika Uniform",
		"Dermatologists Draw Attention to Skin Cancer",
		"The Debate Over Voting-Boothe Selfies"],
	m1 =["Weekend"],a30 =["Weekend"],
	a29 =[	"The Complicated War in Syria",
		"A Dive to the Marianas Trench",
		"Bison Closer to \"National Mammal\" Status After House Vote"],
	a28 =[	"Ted Cruz Names Carly Fiorina as VP Pick",
		"A Shift in Genorational Demographics",
		"Harvard Mumps Outbreak Grows"]
}
